# -*- coding: utf-8 -*-
"""Chubb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMKNvv5EQ_SWAkjsO5pSO_AOwf27kXRY
"""

import pandas as pd
import re
import numpy as np
def convert_range_to_midpoint(value):
    """
    Cleans a string, converts ranges to their midpoint, and handles various formats.
    """
    # Ensure value is a string and convert to lowercase
    s = str(value).lower()

    # Clean the string: remove $, ,, +, and replace 'k' with '000'
    s = s.replace('$', '').replace(',', '').replace('+', '')
    s = re.sub(r'k', '000', s)

    # Check if it's a range (contains a hyphen)
    if '-' in s:
        try:
            parts = s.split('-')
            start = float(parts[0].strip())
            end = float(parts[1].strip())
            return (start + end) / 2
        except (ValueError, IndexError):
            return 0 # Return 0 if range is malformed

    # If not a range, try converting to a single number
    try:
        return float(s.strip())
    except ValueError:
        return 0 # Return 0 if it's a non-numeric string


def preprocessing_data(df , target_col = "Churn" , drop_cols = [] , categorical_encoder='ordinal'):
    print("Preprocessing data...")

    # Combine all columns to be dropped into a single list
    all_cols_to_drop = [col for col in df.columns if col.lower().endswith('_id')]
    if 'Id' in df.columns and 'Id' not in all_cols_to_drop:
        all_cols_to_drop.append('Id')
    all_cols_to_drop.extend(drop_cols) # Add user-specified columns

    # Find which of these columns actually exist in the DataFrame
    existing_cols_to_drop = [col for col in all_cols_to_drop if col in df.columns]

    if existing_cols_to_drop:
        print(f"Dropping the following columns: {existing_cols_to_drop}")
        df = df.drop(columns=existing_cols_to_drop)
    else:
        print("No specified columns to drop were found in the DataFrame.")


    if target_col not in df.columns:
        raise ValueError(f"Target column '{target_col}' not found in the DataFrame.")

    # Handle 'home_market_value' and 'home_owner'
    if "home_owner" not in df.columns:
        if "home_market_value" in df.columns:
            df = df.drop(columns = ["home_market_value"])
        else:
            print("Neither 'home_owner' nor 'home_market_value' found. Skipping related preprocessing.")

    # Handle 'home_owner' if it exists
    if "home_owner" in df.columns:
        # Ensure 'home_owner' is binary (assuming 'yes'/'no' or similar)
        # Convert to numeric: 1 for 'yes', 0 for 'no' or other values
        df['home_owner'] = df['home_owner'].apply(lambda x: 1 if str(x).lower() == 'yes' else (0 if str(x).lower() == 'no' else 0))

    # Apply convert_range_to_midpoint to relevant columns (example columns)
    # You should replace these with the actual columns in your dataset that need this conversion
    range_cols = ['annual_income', 'credit_score'] # Example columns
    for col in range_cols:
        if col in df.columns:
            print(f"Converting ranges to midpoints in column: {col}")
            df[col] = df[col].apply(convert_range_to_midpoint)

    # Handle missing values - Simple imputation example (mean for numeric, mode for categorical)
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype in ['int64', 'float64']:
                print(f"Imputing missing values in numeric column: {col}")
                df[col].fillna(df[col].mean(), inplace=True)
            elif df[col].dtype == 'object':
                print(f"Imputing missing values in categorical column: {col}")
                # Impute with mode, handle potential empty mode result
                mode_val = df[col].mode()
                if not mode_val.empty:
                    df[col].fillna(mode_val[0], inplace=True)
                else:
                     print(f"Could not determine mode for column {col}. Skipping imputation.")


    # Separate features and target
    y = df[target_col]
    X = df.drop(columns=[target_col])

    # Identify categorical and numerical features
    categorical_features = X.select_dtypes(include=['object', 'category']).columns
    numerical_features = X.select_dtypes(include=np.number).columns

    # Handle categorical features
    if not categorical_features.empty:
        print(f"Categorical features found: {list(categorical_features)}")
        if categorical_encoder == 'onehot':
            print("Applying One-Hot Encoding...")
            X = pd.get_dummies(X, columns=categorical_features, drop_first=True)
        elif categorical_encoder == 'ordinal':
            print("Applying Ordinal Encoding...")
            # Simple ordinal encoding using pandas factorize
            for col in categorical_features:
                # Convert to string before factorize to handle mixed types and NaNs
                X[col], _ = pd.factorize(X[col].astype(str))
        else:
            raise ValueError(f"Unknown categorical encoder: {categorical_encoder}. Choose 'onehot' or 'ordinal'.")
    else:
        print("No categorical features found.")

    # Ensure all columns are numeric after encoding
    for col in X.columns:
        if X[col].dtype == 'object':
             print(f"Warning: Column '{col}' is still of object type after encoding. Attempting conversion to numeric.")
             X[col] = pd.to_numeric(X[col], errors='coerce')
             # Impute any new NaNs created by coercion
             if X[col].isnull().any():
                 print(f"Imputing NaNs created by coercion in column: {col}")
                 X[col].fillna(X[col].mean() if X[col].dtype in ['int64', 'float64'] else 0, inplace=True)


    print("Preprocessing complete.")
    return X, y

insurance_df = pd.read_csv("autoinsurance_churn.csv")
X, y = preprocessing_data(insurance_df, target_col = "Churn")

print(X.shape)
print(y.shape)

# churn_training_with_shap_fixed.py
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
import shap
import matplotlib.pyplot as plt

# ----------------------
# reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ----------------------
# Assumes X (pd.DataFrame) and y (pd.Series/array) already exist in the environment.
# If you run as standalone, load X,y here (uncomment & adapt):
# df = pd.read_csv("preprocessed.csv")
# y = df['Churn'].astype(int).values
# X = df.drop(columns=['Churn'])

# Ensure y is a 1D numpy int array
if isinstance(y, (pd.Series, pd.DataFrame)):
    y = np.asarray(y).reshape(-1)
else:
    y = np.asarray(y).reshape(-1)
y = y.astype(int)

# Keep feature names before converting X to numpy
feature_names = list(X.columns) if hasattr(X, "columns") else [f"f{i}" for i in range(X.shape[1])]
X = np.asarray(X).astype(np.float32)

# ----------------------
# Train / val / test split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.25, random_state=SEED, stratify=y_train
)  # 0.25 * 0.8 = 0.2

# ----------------------
# Torch Dataset / DataLoader
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).view(-1, 1)
    def __len__(self):
        return len(self.y)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

BATCH_SIZE = 256
train_loader = DataLoader(TabularDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader   = DataLoader(TabularDataset(X_val,   y_val),   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(TabularDataset(X_test,  y_test),  batch_size=BATCH_SIZE, shuffle=False)

# ----------------------
# MLP model (simple but effective)
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dims=[256,128,64], dropout=0.3):
        super().__init__()
        layers = []
        d_in = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(d_in, h))
            layers.append(nn.ReLU())
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.Dropout(p=dropout))
            d_in = h
        layers.append(nn.Linear(d_in, 1))  # single logit for binary classification
        self.net = nn.Sequential(*layers)
    def forward(self, x):
        return self.net(x)  # logits (no sigmoid)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MLP(input_dim=X.shape[1], hidden_dims=[256,128,64], dropout=0.25).to(device)

# ----------------------
# Loss, optimizer, scheduler
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)

# ----------------------
# Training loop with early stopping
EPOCHS = 100
early_stop_patience = 10
best_val_loss = float('inf')
epochs_no_improve = 0
best_state = None

def evaluate(model, loader):
    model.eval()
    ys, probs = [], []
    losses = []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            yb = yb.to(device)
            logits = model(xb)                     # logits on device
            prob = torch.sigmoid(logits).cpu().numpy().reshape(-1)
            probs.append(prob)
            ys.append(yb.cpu().numpy().reshape(-1))
            # compute loss per batch using logits (safer numerically)
            loss_batch = criterion(logits, yb).item()
            losses.append(loss_batch)
    y_true = np.concatenate(ys) if len(ys) > 0 else np.array([])
    y_prob = np.concatenate(probs) if len(probs) > 0 else np.array([])
    avg_loss = float(np.mean(losses)) if len(losses) > 0 else float('nan')
    auc = roc_auc_score(y_true, y_prob) if (len(y_true) > 0 and len(np.unique(y_true)) > 1) else float('nan')
    y_pred_label = (y_prob >= 0.5).astype(int)
    acc = accuracy_score(y_true, y_pred_label) if len(y_true) > 0 else float('nan')
    prec = precision_score(y_true, y_pred_label, zero_division=0) if len(y_true) > 0 else float('nan')
    rec = recall_score(y_true, y_pred_label, zero_division=0) if len(y_true) > 0 else float('nan')
    return {"loss": avg_loss, "auc": auc, "acc": acc, "prec": prec, "rec": rec, "y_true": y_true, "y_prob": y_prob}

for epoch in range(1, EPOCHS + 1):
    model.train()
    epoch_losses = []
    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)
        optimizer.zero_grad()
        logits = model(xb)               # logits
        loss = criterion(logits, yb)     # BCEWithLogits
        loss.backward()
        optimizer.step()
        epoch_losses.append(loss.item())
    train_loss = float(np.mean(epoch_losses)) if len(epoch_losses) > 0 else float('nan')
    val_metrics = evaluate(model, val_loader)
    val_loss = val_metrics["loss"]
    print(f"Epoch {epoch:03d} | train_loss: {train_loss:.4f} | val_loss: {val_loss:.4f} | val_auc: {val_metrics['auc']:.4f} | val_acc: {val_metrics['acc']:.4f}")
    scheduler.step(val_loss)
    # early stopping
    if val_loss < best_val_loss - 1e-6:
        best_val_loss = val_loss
        epochs_no_improve = 0
        best_state = {k:v.cpu().clone() for k,v in model.state_dict().items()}  # save CPU copy
        torch.save(best_state, "best_churn_model.pth")
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= early_stop_patience:
            print(f"Early stopping triggered after {epoch} epochs.")
            break

# Load best model
if best_state is not None:
    model.load_state_dict(best_state)
    model.to(device)

# ----------------------
# Final evaluation on test set
test_metrics = evaluate(model, test_loader)
print("\nTest set results:")
print(f"Test loss: {test_metrics['loss']:.4f}")
print(f"Test AUC: {test_metrics['auc']:.4f}")
print(f"Test Acc: {test_metrics['acc']:.4f}, Precision: {test_metrics['prec']:.4f}, Recall: {test_metrics['rec']:.4f}")

# ----------------------
# Predict function (batch predict on numpy inputs)
def predict_proba_numpy(model, X_np, batch_size=1024):
    model.eval()
    probs = []
    with torch.no_grad():
        for i in range(0, X_np.shape[0], batch_size):
            xb = torch.tensor(X_np[i:i+batch_size], dtype=torch.float32).to(device)
            logits = model(xb)
            probs.append(torch.sigmoid(logits).cpu().numpy())
    return np.vstack(probs).reshape(-1)

# Example: get churn probabilities for test set
test_probs = predict_proba_numpy(model, X_test)
# Save example predictions
pd.DataFrame({"y_true": y_test, "y_prob": test_probs}).to_csv("test_predictions.csv", index=False)

# ----------------------
# SHAP explainability (KernelExplainer)
# KernelExplainer is model-agnostic but can be slow. Use a small background sample.
print("Computing SHAP values (this may take time)...")
background_size = min(50, X_train.shape[0])
background_idx = np.random.choice(np.arange(X_train.shape[0]), size=background_size, replace=False)
background = X_train[background_idx]

# Prediction wrapper expects 2D numpy array -> returns vector of probabilities
def predict_fn_np(x_np):
    # ensure float32 and contiguous
    x_np = np.asarray(x_np, dtype=np.float32)
    return predict_proba_numpy(model, x_np, batch_size=2048)

# initialize explainer
explainer = shap.KernelExplainer(predict_fn_np, background)

# compute shap values for a subset (e.g., 200 samples or test set size whichever smaller)
shap_sample_size = min(200, X_test.shape[0])
test_idx_for_shap = np.random.choice(np.arange(X_test.shape[0]), size=shap_sample_size, replace=False)
X_shap = X_test[test_idx_for_shap]

# nsamples controls runtime/accuracy; increase if you have time
shap_values = explainer.shap_values(X_shap, nsamples=200)

# KernelExplainer may return list for binary problems; unify into array
if isinstance(shap_values, list) and len(shap_values) == 1:
    shap_values = shap_values[0]

# Summary plot (be careful: shap.summary_plot calls show by default)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_shap, feature_names=feature_names, show=True)
plt.savefig("shap_summary_plot.png", bbox_inches="tight")
plt.close()

# Per-sample force plot example (for first sample)
i = 0
shap.initjs()
# Using matplotlib=True returns a matplotlib.figure (in newer shap versions)
force_fig = shap.force_plot(explainer.expected_value, shap_values[i], X_shap[i], feature_names=feature_names, matplotlib=True)
if hasattr(force_fig, "savefig"):
    force_fig.savefig("shap_force_plot_sample0.png", bbox_inches="tight")
else:
    # fallback: save HTML force plot
    html = shap.force_plot(explainer.expected_value, shap_values[i], X_shap[i], feature_names=feature_names)
    with open("shap_force_plot_sample0.html", "w") as f:
        f.write(html.html())

print("SHAP computations done. Saved: shap_summary_plot.png, shap_force_plot_sample0.png/html")
print("Saved best model as best_churn_model.pth and test predictions as test_predictions.csv")
# churn_training_with_shap_fixed.py
import os
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
import shap
import matplotlib.pyplot as plt

# ----------------------
# reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ----------------------
# Assumes X (pd.DataFrame) and y (pd.Series/array) already exist in the environment.
# If you run as standalone, load X,y here (uncomment & adapt):
# df = pd.read_csv("preprocessed.csv")
# y = df['Churn'].astype(int).values
# X = df.drop(columns=['Churn'])

# Ensure y is a 1D numpy int array
if isinstance(y, (pd.Series, pd.DataFrame)):
    y = np.asarray(y).reshape(-1)
else:
    y = np.asarray(y).reshape(-1)
y = y.astype(int)

# Keep feature names before converting X to numpy
feature_names = list(X.columns) if hasattr(X, "columns") else [f"f{i}" for i in range(X.shape[1])]
X = np.asarray(X).astype(np.float32)

# ----------------------
# Train / val / test split (stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train, test_size=0.25, random_state=SEED, stratify=y_train
)  # 0.25 * 0.8 = 0.2

# ----------------------
# Torch Dataset / DataLoader
class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).view(-1, 1)
    def __len__(self):
        return len(self.y)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

BATCH_SIZE = 256
train_loader = DataLoader(TabularDataset(X_train, y_train), batch_size=BATCH_SIZE, shuffle=True, drop_last=False)
val_loader   = DataLoader(TabularDataset(X_val,   y_val),   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(TabularDataset(X_test,  y_test),  batch_size=BATCH_SIZE, shuffle=False)

# ----------------------
# MLP model (simple but effective)
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dims=[256,128,64], dropout=0.3):
        super().__init__()
        layers = []
        d_in = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(d_in, h))
            layers.append(nn.ReLU())
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.Dropout(p=dropout))
            d_in = h
        layers.append(nn.Linear(d_in, 1))  # single logit for binary classification
        self.net = nn.Sequential(*layers)
    def forward(self, x):
        return self.net(x)  # logits (no sigmoid)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = MLP(input_dim=X.shape[1], hidden_dims=[256,128,64], dropout=0.25).to(device)

# ----------------------
# Loss, optimizer, scheduler
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=4)

# ----------------------
# Training loop with early stopping
EPOCHS = 100
early_stop_patience = 10
best_val_loss = float('inf')
epochs_no_improve = 0
best_state = None

def evaluate(model, loader):
    model.eval()
    ys, probs = [], []
    losses = []
    with torch.no_grad():
        for xb, yb in loader:
            xb = xb.to(device)
            yb = yb.to(device)
            logits = model(xb)                     # logits on device
            prob = torch.sigmoid(logits).cpu().numpy().reshape(-1)
            probs.append(prob)
            ys.append(yb.cpu().numpy().reshape(-1))
            # compute loss per batch using logits (safer numerically)
            loss_batch = criterion(logits, yb).item()
            losses.append(loss_batch)
    y_true = np.concatenate(ys) if len(ys) > 0 else np.array([])
    y_prob = np.concatenate(probs) if len(probs) > 0 else np.array([])
    avg_loss = float(np.mean(losses)) if len(losses) > 0 else float('nan')
    auc = roc_auc_score(y_true, y_prob) if (len(y_true) > 0 and len(np.unique(y_true)) > 1) else float('nan')
    y_pred_label = (y_prob >= 0.5).astype(int)
    acc = accuracy_score(y_true, y_pred_label) if len(y_true) > 0 else float('nan')
    prec = precision_score(y_true, y_pred_label, zero_division=0) if len(y_true) > 0 else float('nan')
    rec = recall_score(y_true, y_pred_label, zero_division=0) if len(y_true) > 0 else float('nan')
    return {"loss": avg_loss, "auc": auc, "acc": acc, "prec": prec, "rec": rec, "y_true": y_true, "y_prob": y_prob}

for epoch in range(1, EPOCHS + 1):
    model.train()
    epoch_losses = []
    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)
        optimizer.zero_grad()
        logits = model(xb)               # logits
        loss = criterion(logits, yb)     # BCEWithLogits
        loss.backward()
        optimizer.step()
        epoch_losses.append(loss.item())
    train_loss = float(np.mean(epoch_losses)) if len(epoch_losses) > 0 else float('nan')
    val_metrics = evaluate(model, val_loader)
    val_loss = val_metrics["loss"]
    print(f"Epoch {epoch:03d} | train_loss: {train_loss:.4f} | val_loss: {val_loss:.4f} | val_auc: {val_metrics['auc']:.4f} | val_acc: {val_metrics['acc']:.4f}")
    scheduler.step(val_loss)
    # early stopping
    if val_loss < best_val_loss - 1e-6:
        best_val_loss = val_loss
        epochs_no_improve = 0
        best_state = {k:v.cpu().clone() for k,v in model.state_dict().items()}  # save CPU copy
        torch.save(best_state, "best_churn_model.pth")
    else:
        epochs_no_improve += 1
        if epochs_no_improve >= early_stop_patience:
            print(f"Early stopping triggered after {epoch} epochs.")
            break

# Load best model
if best_state is not None:
    model.load_state_dict(best_state)
    model.to(device)

# ----------------------
# Final evaluation on test set
test_metrics = evaluate(model, test_loader)
print("\nTest set results:")
print(f"Test loss: {test_metrics['loss']:.4f}")
print(f"Test AUC: {test_metrics['auc']:.4f}")
print(f"Test Acc: {test_metrics['acc']:.4f}, Precision: {test_metrics['prec']:.4f}, Recall: {test_metrics['rec']:.4f}")

# ----------------------
# Predict function (batch predict on numpy inputs)
def predict_proba_numpy(model, X_np, batch_size=1024):
    model.eval()
    probs = []
    with torch.no_grad():
        for i in range(0, X_np.shape[0], batch_size):
            xb = torch.tensor(X_np[i:i+batch_size], dtype=torch.float32).to(device)
            logits = model(xb)
            probs.append(torch.sigmoid(logits).cpu().numpy())
    return np.vstack(probs).reshape(-1)

# Example: get churn probabilities for test set
test_probs = predict_proba_numpy(model, X_test)
# Save example predictions
pd.DataFrame({"y_true": y_test, "y_prob": test_probs}).to_csv("test_predictions.csv", index=False)

# ----------------------
# SHAP explainability (KernelExplainer)
# KernelExplainer is model-agnostic but can be slow. Use a small background sample.
print("Computing SHAP values (this may take time)...")
background_size = min(50, X_train.shape[0])
background_idx = np.random.choice(np.arange(X_train.shape[0]), size=background_size, replace=False)
background = X_train[background_idx]

# Prediction wrapper expects 2D numpy array -> returns vector of probabilities
def predict_fn_np(x_np):
    # ensure float32 and contiguous
    x_np = np.asarray(x_np, dtype=np.float32)
    return predict_proba_numpy(model, x_np, batch_size=2048)

# initialize explainer
explainer = shap.KernelExplainer(predict_fn_np, background)

# compute shap values for a subset (e.g., 200 samples or test set size whichever smaller)
shap_sample_size = min(200, X_test.shape[0])
test_idx_for_shap = np.random.choice(np.arange(X_test.shape[0]), size=shap_sample_size, replace=False)
X_shap = X_test[test_idx_for_shap]

# nsamples controls runtime/accuracy; increase if you have time
shap_values = explainer.shap_values(X_shap, nsamples=200)

# KernelExplainer may return list for binary problems; unify into array
if isinstance(shap_values, list) and len(shap_values) == 1:
    shap_values = shap_values[0]

# Summary plot (be careful: shap.summary_plot calls show by default)
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values, X_shap, feature_names=feature_names, show=True)
plt.savefig("shap_summary_plot.png", bbox_inches="tight")
plt.close()

# Per-sample force plot example (for first sample)
i = 0
shap.initjs()
# Using matplotlib=True returns a matplotlib.figure (in newer shap versions)
force_fig = shap.force_plot(explainer.expected_value, shap_values[i], X_shap[i], feature_names=feature_names, matplotlib=True)
if hasattr(force_fig, "savefig"):
    force_fig.savefig("shap_force_plot_sample0.png", bbox_inches="tight")
else:
    # fallback: save HTML force plot
    html = shap.force_plot(explainer.expected_value, shap_values[i], X_shap[i], feature_names=feature_names)
    with open("shap_force_plot_sample0.html", "w") as f:
        f.write(html.html())

print("SHAP computations done. Saved: shap_summary_plot.png, shap_force_plot_sample0.png/html")
print("Saved best model as best_churn_model.pth and test predictions as test_predictions.csv")

